# Generated by Django 5.1.7 on 2025-03-31 13:35

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_servicos_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumbnail': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Foto de perfil'),
        ),
    ]
